// Generated by gencpp from file custom_msgs/robotInfo.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ROBOTINFO_H
#define CUSTOM_MSGS_MESSAGE_ROBOTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct robotInfo_
{
  typedef robotInfo_<ContainerAllocator> Type;

  robotInfo_()
    : header()
    , motor_state(0)
    , voltage(0.0)
    , linear_x(0.0)
    , linear_y(0.0)
    , linear_z(0.0)
    , angular_x(0.0)
    , angular_y(0.0)
    , angular_z(0.0)  {
    }
  robotInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor_state(0)
    , voltage(0.0)
    , linear_x(0.0)
    , linear_y(0.0)
    , linear_z(0.0)
    , angular_x(0.0)
    , angular_y(0.0)
    , angular_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _motor_state_type;
  _motor_state_type motor_state;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef double _linear_x_type;
  _linear_x_type linear_x;

   typedef double _linear_y_type;
  _linear_y_type linear_y;

   typedef double _linear_z_type;
  _linear_z_type linear_z;

   typedef double _angular_x_type;
  _angular_x_type angular_x;

   typedef double _angular_y_type;
  _angular_y_type angular_y;

   typedef double _angular_z_type;
  _angular_z_type angular_z;





  typedef boost::shared_ptr< ::custom_msgs::robotInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::robotInfo_<ContainerAllocator> const> ConstPtr;

}; // struct robotInfo_

typedef ::custom_msgs::robotInfo_<std::allocator<void> > robotInfo;

typedef boost::shared_ptr< ::custom_msgs::robotInfo > robotInfoPtr;
typedef boost::shared_ptr< ::custom_msgs::robotInfo const> robotInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::robotInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::robotInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/clivewong/github/HCR2018/ROS/main/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::robotInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::robotInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::robotInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::robotInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::robotInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::robotInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::robotInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c36e39f387f1c959a0562f682e3dcd21";
  }

  static const char* value(const ::custom_msgs::robotInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc36e39f387f1c959ULL;
  static const uint64_t static_value2 = 0xa0562f682e3dcd21ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::robotInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/robotInfo";
  }

  static const char* value(const ::custom_msgs::robotInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::robotInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# robotInfo.msg\n\
\n\
Header header\n\
int32 motor_state\n\
float32 voltage\n\
# Linear/ Angular velocities \n\
float64 linear_x\n\
float64 linear_y\n\
float64 linear_z\n\
float64 angular_x\n\
float64 angular_y\n\
float64 angular_z\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::custom_msgs::robotInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::robotInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor_state);
      stream.next(m.voltage);
      stream.next(m.linear_x);
      stream.next(m.linear_y);
      stream.next(m.linear_z);
      stream.next(m.angular_x);
      stream.next(m.angular_y);
      stream.next(m.angular_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::robotInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::robotInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_state);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "linear_x: ";
    Printer<double>::stream(s, indent + "  ", v.linear_x);
    s << indent << "linear_y: ";
    Printer<double>::stream(s, indent + "  ", v.linear_y);
    s << indent << "linear_z: ";
    Printer<double>::stream(s, indent + "  ", v.linear_z);
    s << indent << "angular_x: ";
    Printer<double>::stream(s, indent + "  ", v.angular_x);
    s << indent << "angular_y: ";
    Printer<double>::stream(s, indent + "  ", v.angular_y);
    s << indent << "angular_z: ";
    Printer<double>::stream(s, indent + "  ", v.angular_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ROBOTINFO_H
