export const REQUEST_EYE_POS = 'REQUEST_EYE_POS';
export const RECEIVE_EYE_POS = 'RECEIVE_EYE_POS';
export const RECEIVE_BOX_STATUS = 'RECEIVE_BOX_STATUS';
export const REQUEST_BOX_OPEN = 'REQUEST_BOX_OPEN';
